### ISSUE TITLE
Installation instructions no longer accessible

### ISSUE THREAD

**Issue by lightshifted** [robertbodley/Quora-500-Technical-Questions-Done#1]
The installation instructions on Quora are no longer accessible: 
http://feedback.livereload.com/knowledgebase/articles/85889-chrome-extensions-apps-and-user-scripts-cannot

**Comment by robertbodley** [comment]
Try this link: https://web.archive.org/web/20160315030240/http://feedback.livereload.com/knowledgebase/articles/85889-chrome-extensions-apps-and-user-scripts-cannot

**Comment by robertbodley** [comment]
I have updated the comment, thanks!
